/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enigma;

import java.io.BufferedOutputStream;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.StringReader;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import static java.sql.JDBCType.NULL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eltix
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */    
    DatagramSocket socet, socketIn;
    InetAddress  address;
    
    public Interface() throws SocketException, UnknownHostException {
       
            socet = new DatagramSocket();
            address = InetAddress.getByName("localhost");
            socketIn = new DatagramSocket(26);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        InText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        OutText = new javax.swing.JTextArea();
        SaveBnt = new javax.swing.JButton();
        OpenBnt = new javax.swing.JButton();
        StartBnt = new javax.swing.JButton();
        FirsKey = new javax.swing.JFormattedTextField();
        SecondKey = new javax.swing.JFormattedTextField();
        ThirdKey = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enigma \"ALMAZ EDITION\"");
        setBackground(new java.awt.Color(240, 128, 128));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 650));

        InText.setBackground(new java.awt.Color(255, 160, 122));
        InText.setColumns(20);
        InText.setFont(new java.awt.Font("Segoe UI Black", 0, 15)); // NOI18N
        InText.setForeground(new java.awt.Color(255, 255, 255));
        InText.setRows(5);
        InText.setCaretColor(new java.awt.Color(255, 105, 180));
        InText.setDoubleBuffered(true);
        InText.setSelectionColor(new java.awt.Color(255, 160, 122));
        jScrollPane1.setViewportView(InText);

        OutText.setBackground(new java.awt.Color(255, 160, 122));
        OutText.setColumns(20);
        OutText.setFont(new java.awt.Font("Segoe UI Black", 0, 15)); // NOI18N
        OutText.setForeground(new java.awt.Color(255, 255, 255));
        OutText.setRows(5);
        OutText.setCaretColor(new java.awt.Color(255, 105, 180));
        OutText.setDisabledTextColor(new java.awt.Color(255, 160, 122));
        OutText.setEnabled(false);
        jScrollPane3.setViewportView(OutText);

        SaveBnt.setBackground(new java.awt.Color(240, 128, 114));
        SaveBnt.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        SaveBnt.setForeground(new java.awt.Color(240, 255, 255));
        SaveBnt.setText("СОХРАНИТЬ");
        SaveBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBntActionPerformed(evt);
            }
        });

        OpenBnt.setBackground(new java.awt.Color(240, 128, 114));
        OpenBnt.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        OpenBnt.setForeground(new java.awt.Color(240, 255, 255));
        OpenBnt.setText("ОТКРЫТЬ ФАЙЛ");
        OpenBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenBntActionPerformed(evt);
            }
        });

        StartBnt.setBackground(new java.awt.Color(240, 128, 114));
        StartBnt.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        StartBnt.setForeground(new java.awt.Color(240, 255, 255));
        StartBnt.setText("НАЧАТЬ");
        StartBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartBntActionPerformed(evt);
            }
        });

        FirsKey.setBackground(new java.awt.Color(233, 150, 122));
        FirsKey.setForeground(new java.awt.Color(240, 240, 240));
        FirsKey.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FirsKey.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        FirsKey.setText("0");
        FirsKey.setFont(new java.awt.Font("Segoe Script", 0, 28)); // NOI18N
        FirsKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirsKeyActionPerformed(evt);
            }
        });

        SecondKey.setBackground(new java.awt.Color(233, 150, 122));
        SecondKey.setForeground(new java.awt.Color(240, 240, 240));
        SecondKey.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        SecondKey.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        SecondKey.setText("0");
        SecondKey.setFont(new java.awt.Font("Segoe Script", 0, 28)); // NOI18N
        SecondKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondKeyActionPerformed(evt);
            }
        });

        ThirdKey.setBackground(new java.awt.Color(233, 150, 122));
        ThirdKey.setForeground(new java.awt.Color(240, 240, 240));
        ThirdKey.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ThirdKey.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ThirdKey.setText("0");
        ThirdKey.setFont(new java.awt.Font("Segoe Script", 0, 28)); // NOI18N
        ThirdKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThirdKeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(StartBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(FirsKey, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SecondKey, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ThirdKey, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(OpenBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(SaveBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(StartBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirsKey, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SecondKey, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThirdKey, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpenBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("ENIGMA JAVA EDITION");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenBntActionPerformed
        OpenDialogBox odb      = new OpenDialogBox();
        String FileName        = odb.DialogOpen("txt");
        if(FileName != null){
        try {
            InText.read(new FileReader(FileName), NULL);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_OpenBntActionPerformed

    private void SaveBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBntActionPerformed
        
        OpenDialogBox odb      = new OpenDialogBox();
        String FileName        = odb.DialogOpen("txt") + ".txt";
         if(FileName != null){
        try {
            BufferedWriter out = new BufferedWriter(new FileWriter(FileName));
                    out.write(OutText.getText());
                    out.close();
                    JOptionPane.showMessageDialog(this, "Файл сохранён");
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
         }
    }//GEN-LAST:event_SaveBntActionPerformed

    private void FirsKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirsKeyActionPerformed
       Long a = (Long)FirsKey.getValue();
       if(a == null){
           FirsKey.setValue(0);
       }
       if(a < 61){
           JOptionPane.showMessageDialog(this, "Введено слишком большое значение ротора");
       FirsKey.setValue(0);
       }
    }//GEN-LAST:event_FirsKeyActionPerformed

    private void SecondKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondKeyActionPerformed
       Long a = (Long)SecondKey.getValue();
       if(a == null){
           SecondKey.setValue(0);
       }
              if(a < 61){
           JOptionPane.showMessageDialog(this, "Введено слишком большое значение ротора");
       SecondKey.setValue(0);
       }
    }//GEN-LAST:event_SecondKeyActionPerformed

    private void ThirdKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThirdKeyActionPerformed
       Long a = (Long)ThirdKey.getValue();
       if(a == null){
           ThirdKey.setValue(0);
       }
              if(a < 61){
           JOptionPane.showMessageDialog(this, "Введено слишком большое значение ротора");
       ThirdKey.setValue(0);
       }
    }//GEN-LAST:event_ThirdKeyActionPerformed

    private void StartBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBntActionPerformed
       String TextToEncode = InText.getText();
            byte[] buf;
             buf = TextToEncode.getBytes();
             
             Long a = (Long)FirsKey.getValue();
             if(a == null)
                 a = Long.valueOf(0);
             
             Long b = (Long)SecondKey.getValue();
             if(b == null)
                b = Long.valueOf(0);
             
             Long c = (Long)ThirdKey.getValue();
             if(c == null)
                c = Long.valueOf(0);
             
             if(a > 61 || b > 61 || c > 61 ){
                  JOptionPane.showMessageDialog(this, "Введено слишком большое значение ротора");
                  return;
             }
             int SizeOfText = buf.length;
             String lendth = String.valueOf(SizeOfText) + " " + a + " " +
                     b + " " + c;
             byte[] LendthBuf = lendth.getBytes();
             DatagramPacket packet = new DatagramPacket(LendthBuf, LendthBuf.length, address, 17);
            JThread CatchCodedText = new JThread("CatchCodedText", SizeOfText, socketIn);
            CatchCodedText.start();
        try {
            socet.send(packet);
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
        packet = new DatagramPacket(buf, buf.length, address, 17);
        try {
            socet.send(packet);

        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_StartBntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Interface().setVisible(true);
                } catch (SocketException ex) {
                    Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

       class OpenDialogBox
   {
       String FileName;
       
        public String DialogOpen(String NameFilter)
        {
            JFileChooser chooser           = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "txt", NameFilter);
            
            chooser.setFileFilter(filter);
            int returnVal = chooser.showOpenDialog(null);
            
            if(returnVal == JFileChooser.APPROVE_OPTION) 
            {
                FileName = chooser.getSelectedFile().getAbsolutePath();
            } 
            
            return FileName;
        }
   }
       
           class JThread extends Thread
    {
        int size;
        DatagramSocket socket;
        JThread(String name, int _size, DatagramSocket soc)
        {
            super(name);
            size = _size;
           socket = soc;
        }
        
        public void run()
        {

            for(int i = 0; i < size; i++)
            {
                 
            byte[] buffer = new byte[size];
            DatagramPacket request = new DatagramPacket(buffer, buffer.length);
                try {
                    socket.receive(request);
                    String CodedText =  new String(request.getData(), 0, request.getLength());
                   OutText.read(new StringReader(CodedText), null);
                   
                } catch (IOException ex) {
                    Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            socket.close();
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FirsKey;
    private javax.swing.JTextArea InText;
    private javax.swing.JButton OpenBnt;
    private javax.swing.JTextArea OutText;
    private javax.swing.JButton SaveBnt;
    private javax.swing.JFormattedTextField SecondKey;
    private javax.swing.JButton StartBnt;
    private javax.swing.JFormattedTextField ThirdKey;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
